//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dentistry
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dentalEntities : DbContext
    {
        private static dentalEntities _context;

        public static dentalEntities GetContext()
        {
            if(_context == null ) 
                _context = new dentalEntities();    
            return _context;
        }

        public dentalEntities()
            : base("name=dentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Role_> Role_ { get; set; }
        public virtual DbSet<Service_> Service_ { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Times> Times { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
