//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dentistry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id_request { get; set; }
        public Nullable<int> id_worker { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_service { get; set; }
        public Nullable<int> id_price { get; set; }
        public Nullable<int> id_time { get; set; }
        public string comments { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Price Price { get; set; }
        public virtual Service_ Service_ { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Times Times { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
